name: Build & Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: denolib/setup-deno@master
        with:
          deno-version: 1.9.2
      - name: Install Velociraptor
        run: |
          deno install -qA -n vr https://deno.land/x/velociraptor@1.0.0-beta.18/cli.ts
          echo "$HOME/.deno/bin" >> $GITHUB_PATH
      - name: Build
        run: vr build
      - name: Test
        run: vr test
